version: '3.8'

services:
  go-app:
    image: go-app:latest
    ports:
      - "5002:5002"
  
  nextjs-app:
    image: nextjs-app:latest
    ports:
      - "3000:3000"
  
  wordpress-site:
    image: wordpress-site:latest
    ports:
      - "80:80"