name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push go-app image
        run: |
          docker build -t your-dockerhub-username/go-app:latest -f go-app/Dockerfile go-app/
          docker push your-dockerhub-username/go-app:latest

      - name: Build and push nextjs-app image
        run: |
          docker build -t your-dockerhub-username/nextjs-app:latest -f nextjs-app/Dockerfile nextjs-app/
          docker push your-dockerhub-username/nextjs-app:latest

      - name: Build and push wordpress-site image
        run: |
          docker build -t your-dockerhub-username/wordpress-site:latest -f wordpress-site/Dockerfile wordpress-site/
          docker push your-dockerhub-username/wordpress-site:latest
