name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Next.js App
        uses: docker/build-push-action@v2
        with:
          context: ./nextjs-app
          file: ./nextjs-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nextjs-app:latest

      - name: Build and Push Go App
        uses: docker/build-push-action@v2
        with:
          context: ./go-app
          file: ./go-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go-app:latest

      - name: Build and Push WordPress Site
        uses: docker/build-push-action@v2
        with:
          context: ./wordpress-site
          file: ./wordpress-site/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wordpress-site:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull and Run Next.js App
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nextjs-app:latest
          docker run -d -p 3000:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/nextjs-app:latest

      - name: Pull and Run Go App
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/go-app:latest
          docker run -d -p 5002:5002 ${{ secrets.DOCKER_HUB_USERNAME }}/go-app:latest

      - name: Pull and Run WordPress Site
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/wordpress-site:latest
          docker run -d -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/wordpress-site:latest
